version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: testing

  backend:
    build: ./backend
    volumes:
      - "./api:/app"
    environment:
      DB_CONNECTION_STRING: postgres://user:password@db:5432/testing
    depends_on:
      - 'db'
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    depends_on:
      - 'backend'
    ports:
      - '3000:3000'
